# Generated by Django 5.2.4 on 2025-07-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг категории')),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=20, verbose_name='Название профессии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание профессии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='professions/', verbose_name='Изображение профессии')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг профессии')),
            ],
        ),
    ]
