# Generated by Django 5.2.4 on 2026-01-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_delete_bestpedagog'),
        ('luceum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.profession')),
            ],
        ),
    ]
