# Generated by Django 5.2.4 on 2025-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luceum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedagog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя педагога')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pedagogs/', verbose_name='Изображение педагога')),
            ],
        ),
    ]
