# Generated by Django 5.2.4 on 2025-07-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luceum', '0002_pedagog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedagog',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание педагога'),
        ),
    ]
