# Generated by Django 5.2.4 on 2026-01-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luceum', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
