# Generated by Django 5.2.4 on 2025-07-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luceum', '0003_pedagog_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestpedagog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя лучшего педагога')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bestpedagogs/', verbose_name='Изображение лучшего педагога')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание лучшего педагога')),
            ],
        ),
    ]
