# Generated by Django 5.2.4 on 2026-01-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luceum', '0003_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=20, verbose_name='Название профессии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание профессии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='professions/', verbose_name='Изображение профессии')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг профессии')),
            ],
        ),
    ]
