# Generated by Django 5.2.4 on 2025-07-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luceum', '0004_bestpedagog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Изображение курса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена курса')),
            ],
        ),
    ]
