# Generated by Django 6.1 on 2026-08-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luceum', '0004_professi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок новости')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='hero_images/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Слайд на главной',
                'verbose_name_plural': 'Слайды на главной',
                'ordering': ['-created_at'],
            },
        ),
    ]
