# Generated by Django 5.2.4 on 2025-07-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luceum', '0005_curss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curss',
            name='description',
        ),
        migrations.AddField(
            model_name='curss',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Длительность курса'),
        ),
    ]
