# Generated by Django 6.1 on 2026-08-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luceum', '0005_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='title',
        ),
    ]
