# Generated by Django 5.2.4 on 2025-08-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luceum', '0006_remove_curss_description_curss_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название учреждения')),
                ('description', models.TextField(verbose_name='Текст о лицее')),
                ('title', models.CharField(max_length=100, verbose_name='Тема маркера')),
                ('title2', models.CharField(max_length=100, verbose_name='Подзаголовки')),
            ],
        ),
    ]
