# Generated by Django 5.2.4 on 2025-08-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luceum', '0007_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('button_primary_text', models.CharField(max_length=50, verbose_name='Переход о нас')),
                ('button_primary_url', models.CharField(max_length=200, verbose_name='Ссылка на регистрацию')),
            ],
        ),
    ]
