# Generated by Django 5.2.4 on 2025-08-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название учреждения')),
                ('description', models.TextField(verbose_name='Текст о лицее')),
                ('title', models.CharField(max_length=100, verbose_name='Тема маркера')),
                ('title2', models.CharField(max_length=100, verbose_name='Подзаголовки')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название достижения')),
                ('description', models.TextField(verbose_name='Описание достижения')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Bestpedagog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя лучшего педагога')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bestpedagogs/', verbose_name='Изображение лучшего педагога')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание лучшего педагога')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название курса')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Длительность курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Изображение курса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена курса')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок истории')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание истории')),
            ],
            options={
                'verbose_name': 'История учреждения',
                'verbose_name_plural': 'История учреждения',
            },
        ),
        migrations.CreateModel(
            name='Pedagog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя педагога')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pedagogs/', verbose_name='Изображение педагога')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание педагога')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=20, verbose_name='Название профессии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание профессии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='professions/', verbose_name='Изображение профессии')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг профессии')),
            ],
        ),
    ]
