# Generated by Django 5.2.4 on 2025-08-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_achievement_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name_plural': 'Достижения'},
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='title',
        ),
    ]
