# Generated by Django 5.2.4 on 2025-08-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_achievement_options_remove_achievement_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bestpedagog',
        ),
    ]
