# Generated by Django 6.1 on 2026-08-15 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_delete_bestpedagog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория книг',
                'verbose_name_plural': 'Категории книг',
            },
        ),
        migrations.CreateModel(
            name='DigitalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название ресурса/портала')),
                ('url', models.URLField(verbose_name='Ссылка на ресурс')),
                ('description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('icon_class', models.CharField(default='fa-globe', max_length=50, verbose_name='Иконка FontAwesome (напр. fa-book)')),
            ],
            options={
                'verbose_name': 'Электронный ресурс',
                'verbose_name_plural': 'Электронные ресурсы',
            },
        ),
        migrations.CreateModel(
            name='LibraryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('image', models.ImageField(upload_to='library/events/', verbose_name='Фото мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время проведения')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия и выставки',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='library/covers/', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='library/pdfs/', verbose_name='Электронная версия (PDF)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна в печатном виде')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='content.bookcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Каталог книг',
            },
        ),
    ]
