# Generated by Django 6.1 on 2026-08-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_bookcategory_digitalresource_libraryevent_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ (FAQ)',
                'verbose_name_plural': 'Вопросы и ответы (FAQ)',
            },
        ),
        migrations.CreateModel(
            name='DormitoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название удобства')),
                ('description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('icon_class', models.CharField(default='fa-wifi', max_length=50, verbose_name='Иконка FontAwesome (напр. fa-wifi, fa-shield-alt, fa-utensils)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Удобство / Преимущество',
                'verbose_name_plural': 'Удобства общежития',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название зоны/комнаты')),
                ('capacity', models.CharField(blank=True, help_text="Например: '2-3 места', 'Общая зона', 'Для парней'", max_length=100, verbose_name='Вместимость/Тип')),
                ('image', models.ImageField(upload_to='dormitory/rooms/', verbose_name='Фотография')),
                ('description', models.TextField(verbose_name='Описание условий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Комната / Помещение',
                'verbose_name_plural': 'Комнаты и помещения',
            },
        ),
        migrations.CreateModel(
            name='DormitoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(help_text="Например: '07:00 - 08:00' или 'После 22:00'", max_length=100, verbose_name='Время / Период')),
                ('title', models.CharField(max_length=200, verbose_name='Действие / Правило')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Подробности')),
            ],
            options={
                'verbose_name': 'Правило / Распорядок',
                'verbose_name_plural': 'Распорядок дня и правила',
            },
        ),
    ]
